services:
  - type: web
    name: urbanroots-nursery
    runtime: docker
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: urbanroots-nursery.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://urbanroots-nursery.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: urbanroots-db
          property: connectionString
    healthCheckPath: /api/nursery/

databases:
  - name: urbanroots-db
    plan: free
