services:
  - type: web
    name: urbanroots-nursery
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "80"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "urbanroots-nursery.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://urbanroots-nursery.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: urbanroots-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
    healthCheckPath: /api/trees/

databases:
  - name: urbanroots-db
    plan: free
